/***** Script for SelectTopNRows command from SSMS  *****/
SELECT TOP 1000 [Id]
      ,[Title]
      ,[Message]
      ,[CreatedOn]
      ,[CreatedFor]
      ,[IsViewed]
  FROM [smartpro].[dbo].[Notifications]
/***** Script for SelectTopNRows command from SSMS  *****/
SELECT TOP 1000 [Id]
      ,[ContractorId]
      ,[CompanyId]
  FROM [smartpro].[dbo].[ContractorMapping]
/***** Script for SelectTopNRows command from SSMS  *****/
SELECT TOP 1000 [Id]
  ,[RequestId]
  ,[ContractorId]
  ,[Value]
  ,[Distance]
  ,[SuggestedBy]
  ,[ContractorDesc]
FROM [smartprooct].[dbo].[ContractorRequestList]
/***** Script for SelectTopNRows command from SSMS  *****/
SELECT TOP 1000 [Id]
  ,[CustomerId]
  ,[ProjectId]
  ,[Descriptions]
  ,[RequestTo]
  ,[SubmittedDate]
  ,[ApprovedTo]
  ,[ApprovedDate]
  ,[IsConsultantApproved]
  ,[RequestCreatedBy]
  ,[NeedSuggestfromCust]
  ,[CompanyId]
  ,[TenderOpeningDateTime]
  ,[Minprice]
  ,[MaxPrice]
FROM [smartpro].[dbo].[ContractorRequest]
/***** Script for SelectTopNRows command from SSMS  *****/
SELECT TOP 1000 [ID]
      ,[CompanyID]
      ,[DivisionID]
      ,[ProjectID]
      ,[StepId]
      ,[ProjectName]
      ,[Elements]
      ,[CustomerId]
      ,[CrockeyUrl]
      ,[BudgetLimit]
      ,[Location]
      ,[City]
      ,[ProjectHandler]
      ,[FloorLevel]
      ,[ProjectTypeId]
      ,[StepStatusId]
      ,[StepNotes]
      ,[StepLog]
      ,[StepStartDate]
      ,[StepDueDate]
      ,[StepComplete]
      ,[StepCompleteDate]
      ,[StepHandler]
      ,[DirectToTender]
      ,[LockedBy]
      ,[LockTS]
      ,[StepOpened]
      ,[StepMailMessage]
      ,[StepMailSubject]
      ,[update_timestamp]
      ,[create_timestamp]
      ,[update_originator_id]
      ,[ServiceTypeID]
      ,[ElementsUrl]
      ,[CustomerName]
      ,[Latitude]
      ,[Longitude]
      ,[BudgetLimitFrom]
      ,[BudgetLimitTo]
      ,[ProjectHandlerContractor]
      ,[Dateofopeningfile]
      ,[DirectToTenderReason]
      ,[TypePlan]
      ,[TypeElevation]
      ,[TypeLayout]
      ,[Type3DMax]
      ,[TypeInterior]
      ,[ProjectClosed]
      ,[IsCancel]
      ,[CancelDate]
      ,[CancelNote]
      ,[checkedStepId]
      ,[checkedStepName]
      ,[AddToArctituralDesign]
      ,[MarketerProjectID]
      ,[ProjectPercentage]
      ,[ContractorID]
      ,[country]
      ,[Description]
      ,[ProjectStatusID]
  FROM [smartpro].[dbo].[CompanyAllProjects]
